### ISSUE TITLE
Assign new intake to - assignment not being displayed properly on CC site

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#112]
Intake: Status & Messages on Conference site. Assigned to "intake" but not being displayed properly on Call Center Conference Summary screen. It shows the intake as "xxx xxx".

**Comment by TomOwens5000** [comment]
Went into CC site and created a new client. Entered everything that was required and selected Done. Check on Conference website and, via gmail, the notification came through for intake. Then reassigned Client to Karieo. Notification to her appeared as expected. She the clicked on the link and invoked the Client File for Oscar. Worked as expected the entire way. SO... the XXX XXX is probably a display issue, as it is not precluding everything else from working as expected.

**Comment by josephr5000** [comment]
BY DESIGN.

The CC view shows First Name + Last Name in hopes that is a more human-readable rendition, so you would show up as "Tom Owens" instead of the more cryptic "TomO".  The short form is useful where (a) abbreviation is necessary, and (b) readers are likely to know who you are because they're in the same conference.  It doesn't work as well when folks *outside* your conferences are reading the name, thus the choice here to use full names.

If you look at other conferences, you'll see that full names are listed in the CC view.

If you look at "intaker" I suspect you'll find that you gave first and last names as XXX XXX.
