### ISSUE TITLE
Rename 3 items under Browse Client Files - Search Filters

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#128]
**•	Other Adult** – Should rename to Total Adults
**•	SSN-** Should only be able to search last 4 digits not more. 
**•	Age from** – Should probably have a minimum age filter (perhaps 15 years?) We only track the person who called, usually head of household.

**Comment by josephr5000** [comment]
Re Other Adult, please see #125.

Re SSN, it will search whatever users enter.  If users enter more than 4 it will search those.  It seems perhaps you're concerned to prevent folks from *entering* more than 4...is that it?  If so I'd say that's a design change request, not really in scope for this phase, and best postponed.  What do you think?

Re Age, why have a limit?  Supposing you think you made an error and entered someone age 5 instead of 45 and you want to locate them.  In that case you'd want the ability to search for clients aged 5.

**Comment by josephr5000** [comment]
This is my comment

**Comment by josephr5000** [comment]
Lisa, haven't heard back from you on this.  I'm leaning toward POSTPONE but would like your input.

**Comment by lisabarrientes** [comment]
Postpone
