### ISSUE TITLE
Data disappears when entering new client after searching new client

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#130]
When searching up a client, after entering basic info, and the search brings back nothing, then proceed to “Add New Client”, data disappears, having to re-enter information again. Our current database keeps the information, where you can proceed to finishing client info.  This is an EXTRA step in the process.  
![image](https://cloud.githubusercontent.com/assets/22033172/18287084/86f7762a-742a-11e6-92d8-935195c33e6e.png)

**Comment by josephr5000** [comment]
Let's discuss.  I thought you instructed folks to only enter first 3 of first and last names in the search page, so I'm surprised you would have situations where people would enter all the detail you display above.

If they only do first 3 of first and last, there's less need to copy that since they haven't typed much.

**Comment by josephr5000** [comment]
Discussed at 9/7/16 meeting.  Agreed to BY DESIGN.
