### ISSUE TITLE
Updating client files and changing conferences conflict

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#135]
![image](https://cloud.githubusercontent.com/assets/22033172/18358686/38d8816e-75ab-11e6-884e-9bfc4ed244d8.png)

**Comment by josephr5000** [comment]
You can't.  You have to choose the conference first.  That's why you should do the map lookup on the Browse Clients page so you know what area you're looking for.  You also need to do it there since you might find multiple matches for a given name where the only difference is the conference, and you need to know which file to pick.

**Comment by lisabarrientes** [comment]
This is quite DIFFERENT from what we are currently doing, and I should add a PAIN!  I still find it a PROBLEM, what if the client we are looking for, tells us a change of address AFTER we open the file???  I DO NOT LIKE that this issue has been closed, without further discussion.

**Comment by josephr5000** [comment]
Sorry, please feel free to reopen and add DISCUSS tag if you would like.  I didn't mean to silence you at all.

I understand this is different from what you do now, however the database is fundamentally different from what you use now in that there are SEPARATE FILES for SEPARATE CONFERENCES even if they refer to the same person.  When you start off, you need to decide early on which conference's files you're going to be working with.  Once a client is in one set of files, it can't be moved...you just open a new file in a different conference.

Please re-read the spec on this.  And let me re-emphasize, I'm very happy to discuss further.

**Comment by josephr5000** [comment]
Reopening, to save Lisa one click :-)

**Comment by lisabarrientes** [comment]
Thanks Joseph, I do have several questions that need clarifying.  I'm trying to get a grasp on this, as I am in the midst of making an instruction manual, and as I am doing this, I need to understand what changes or challenges there will be, so I can figure how to add in the solutions. 

**1.**  If I were to search for a client, in the new database, and I happen to enter in the client's last 4 digits of his/her SSN, there is a possibility that I will find more than one file for that same client, and he/she may have different addresses associated with different conferences.  **Correct?**

**2.**  If I find a match for an address for a client in the database, then I pull up that file, I would just enter a request accordingly.  **Correct?**

**3.**  If I locate the client and see several entries for the same client in the database, but he/she gives me an address which is NOT in the selection of the clients listed, then I enter him as a NEW file under a NEW or perhaps the same conference, (depending on the address)?  **Correct?**

With the database we are currently using in the Helpline Center, we are able to view the **Call History** as well as the **Request History** for every client.  

**4.**  With the new database, will we be able to do this, even if we enter in new information for an existing client who will may or may not be in a **DIFFERENT** conference?

**Comment by josephr5000** [comment]
QUESTION 1. There's certainly a possibility you might find multiple matches for the last 4 of the SSN.  The entire number is unique, but the last 4 aren't, so it's entirely possible two *different* callers might coincidentally both have numbers ending in 4480 (for example).  These matches might be: 
(a) same conf, same person (indicating that conference has a duplicate), 
(b) same conf, different people (probably apparent by diff name and DOB), 
(c) different conf but same person (probably helped at different times...perhaps they moved?), or 
(d) different conferences and different people.

Advice:
(a) Pick the one helped most recently.
(b) Pick the one matching the actual person who is calling, or create a new file if it's someone different from any of the matches.
(c) Pick the one in the conference that serves their current address.  If that's different from any of the matches, create a new file in the new conference.
(d) Pick the conference according to their address and the person according to other identifying information like name and DOB.

QUESTION 2. Certainly, provided it's a real match!

QUESTION 3. See #1 above.  You would NOT want to create a new file just because an existing client moves within the SAME conference.  I don't want two LisaB files just because you move a block down the street...I'd just update the address on your existing file.  But if you move to a different conference area I'd have to create a new file in that new conference's area.

In this one you can see the request (and turn-away) history.  We did not put in the spec to have a summary screen showing dates the file was updated (presumably because they called in).  You could file a separate enhnacement request on that if you think it is important.

QUESTION 4. Not totally sure I follow this question.  Please re-read my answers to 1, 2 and 3 above, and then let me know if you still have any questions.

I hope this helps.

**Comment by josephr5000** [comment]
EXTRA COMMENT: after re-reading my reply to Q1 above, it occurs to me the advice could probably be simplified even further, like this:

- STEP ONE: pick a conference based on the caller's current address, *regardless* who they are.

- STEP TWO: within that conference, decide if any existing client is the same person based on DOB, SSN, name, etc.
        IF YES, PERSON EXISTS IN THE FILES, then open the existing file, update other details like addr, phone, income, and note what they are requesting now.  
       IF NO, PERSON DOESN'T ALREADY EXIST, then create a new client file in that conference, and enter this new client's particulars.

**Comment by lisabarrientes** [comment]
STEP ONE would work, but STEP TWO has some conflicts.
- STEP TWO: If the client has a DOB, it does not show on this screen, also some clients may not have or want to use a SSN. IF that's the case, then the search criteria is left with 

- **NAME**

- **Address**

- **Phone**

- **Conference**
 
In the case of Client Name "Steve Knipp", I have edited the one file and added a DOB as well as last 4 digits of  his SSN.  There is no place for a DOB, so you cannot see this.  Also, there are several "St. George" conferences, with the Client Name "Steve Knipp", as well as one "King County Call Center" conference.  In this case all do not have a "Last Helped" indicator listed.  What do we do, open up any file or create a new file?  

The paragraph above QUESTION 4, is what I was referring to for that question, which you answered below:

In this one you can see the request (and turn-away) history. We did not put in the spec to have a summary screen showing dates the file was updated (presumably because they called in). You could file a separate enhnacement request on that if you think it is important.  _Yes, it is important on our end._ 

Also, for issue #137  **_Question about switching Add New Client Screen vs Edit Client Info Screen #137_**

I think this would solve a lot of the issues I have brought up, and would be able to  lessen the affect of duplicate files. Allowing the edits without creating a New Client File.

**Comment by josephr5000** [comment]
So..there's only ONE St George conference, not "several" as you wrote above.  Within that conference you created a bunch of duplicate files for Steve Knipp, none of which have ever been helped, one of which has an SSN.  Faced with this much duplication, if they're really the same person you're free to pick any one of them, but you'd probably also want to ask St George why there are so many duplicates.

Let's talk about issue #137 on that issue.

Are we done with this issue, or are there any remaining questions?

**Comment by lisabarrientes** [comment]
True, but I did not create any of those files. I just edited the one I mentioned.

And please, issue #137, has everthing I need in order to move forward, otherwise I am at a locked state, and cannot continue to use this as it is.

Lisa Barrientes
Helpline Center Manager
St. Vincent de Paul of Seattle|King County
5950 Fourth Avenue South|Seattle, WA 98108
P: 206-767-9975 Ext. 1131
E: lisab@svdpseattle.org<mailto:lisab@svdpseattle.org>

**Comment by josephr5000** [comment]
This doesn't still appear to be a live issue, so I'm closing it.
