### ISSUE TITLE
Excessive requirements to "Update Client Record"

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#157]
When you want to **Add New Request**, you end up looking at this screen, which I think will be a source for errors being made.  Is it possible to remove this step, instead of hitting the **Continue** tab, to get to the request page?
![image](https://cloud.githubusercontent.com/assets/22033172/18645299/7507f818-7e61-11e6-931a-a3d00f50ea71.png)

**Comment by josephr5000** [comment]
It's not a bug...it's intentional.

A big risk is that people just add fresh requests to existing files without updating key profile info like address, phone, etc.

As it says in bright red, this STEP 1 is to make sure the client record is up-to-date before you start recording requests.

Just curious: do you have somewhere else in your workflow that you would do this?  Do you have confidence folks wouldn't forget?

Perhaps this isn't working as intended?  Could you clarify why you think it might be a source of error?  Obviously that would be bad....!

**Comment by josephr5000** [comment]
Have re-evaluated, and I see what Lisa means.  Changed title to reflect the issue, and changed labels from "question" to "bug".

TO REPRO:

1. Press Add New Client, and fill in their particulars
2. Press Continue, and get to the newly created Client File
3. Press Add New Request

PROBLEM: you get the "Confirm Client Details" page that Lisa pictured above.

This is totally unnecessary since you just entered this information minutes ago (seconds, even).  

It is extremely annoying.  It's also easy to misunderstand what is being requested since it's so ridiculous that it would ask the same information twice.

BACKGROUND: there used to be an Add Request button directly at step 2 above, which would avoid this.  On adding Quota features that button went away as it was problematic to confirm the newly quota status at this point in the workflow when their data hadn't even been submitted to the server.

The Add Request button was designed on the assumption you were editing an *existing* file where confirmation would be required, not one you only just created.

SUGGESTED FIX: use the "updated" field on the client's record to figure out when it was last updated.  If that was "recently" (eg: within past 24 hours) then skip the screen that asks for confirmation.

**Comment by josephr5000** [comment]
FIXED.  I did the "SUGGESTED FIX" described above.

@lisabarrientes : your folks should now be able to go from adding a NEW client to adding a request WITHOUT seeing this screen again since that's not necessary.

If they go back to add requests to an EXISTING client whose profile has not been touched recently, they WILL get this screen to give them a chance to reconfirm details with the caller before moving on.

FYI @drodruck @TomOwens5000

**Comment by lisabarrientes** [comment]
Not sure if this is a bug or if it's meant to be that way, but when entering  a new request, you can change the date to a prior date, but not for any future dates.  
![image](https://cloud.githubusercontent.com/assets/22033172/19402107/f58eb0e2-9213-11e6-9fb7-35d8d6d0c8a7.png)

**Comment by josephr5000** [comment]
Please open a separate issue if you want to ask an unrelated question.  It's by design to allow past dates but not future, by the way, but that has nothing to do with the subject line of this issue.  Things get really confusing if unrelated questions pop up in unexpected places.  Thanks.

**Comment by lisabarrientes** [comment]
Got it…sorry I didn’t realize I sent this on an open request.

Lisa Barrientes
Helpline Center Manager
St. Vincent de Paul of Seattle|King County
5950 Fourth Avenue South|Seattle, WA 98108
P: 206-767-9975 Ext. 1131
E: lisab@svdpseattle.org<mailto:lisab@svdpseattle.org>
