### ISSUE TITLE
Call Center - Browse Client Files screen needs a button to bring up list of all clients

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#172]
Scenario
After adding a new client on the Add New Client screen by clicking on Save & Continue (*no progress indicator is working here and searches are again starting to take longer*) ... you get the Client File for the client in question.

But now if for some reason you want to see the list of everyone again you need to close the Client File and then clear all the fields in the Add New Client screen and press Save & Continue again to see a listing of everyone. 

A Back button on that Client File would be a more efficient way to get the list displayed again.
This is only an issue for Call Center people. It is a non-issue on the Conference site.

**Comment by josephr5000** [comment]
You wrote "...if for some reason you want to see the list of everyone again..." which I'm not following.

(1) You wrote "again".  Where had you previously seen a list of EVERYONE?

(2) There are 48,881 clients in King County.  Could you clarify under what circumstances you'd want to see a listing of ALL of them?  

Thanks.

**Comment by josephr5000** [comment]
Haven't heard any reply to my question above, so to keep things moving along I'm closing this as BY DESIGN since I did deliberately omit the "Show All" button for CC users for the reason mentioned above (48,881 clients is far too many to want to view at once).

If you think the design should be changed, can you help me understand the need for this?  Is there a user scenario where this would be missed?
