### ISSUE TITLE
Member Roster has almost not data validation

### ISSUE THREAD

**Issue by DaveSherwood** [josephr5000/confdb-public#178]
There is almost no data validation. There is limited field types. Most field types are text fields so you can put anything you want. Even on the date field, there is no range restrictions. A member could have started in 1750 and it is fine with that.

**Comment by josephr5000** [comment]
There isn't really a date field.  Member since accepts years, year/mo, or year/month/day depending on what level of detail you recall, since many members joined long ago and precise dates are lost in the mists of time.  Other fields are pretty much free-form entry.  If you have specific validation (beyond date) you're expecting, please give details.

**Comment by josephr5000** [comment]
Haven't heard an answer on my request above, however please see #194 that covers the need for the email field to be validated.

In general, if no harm comes from entering odd data I don't forbid it.  The site is very libertarian in that respect.  For the email field, we need to send emails to that address so it needs to be valid.

If you find other fields where harm arises from input not being validated, please yell.  For now I'm going to close this one as by design.
