### ISSUE TITLE
SFH Report Part A - difference in findings

### ISSUE THREAD

**Issue by DaveSherwood** [josephr5000/confdb-public#179]
I passed this report but have a question:
Why does this report show: Telephone only contacts 1 and the SVDP  Report show telephone only contacts as 31 for this fiscal year? Same in both old and new DBs. They can't both be right.

**Comment by josephr5000** [comment]
FIXED.

Interesting!  This same bug exists on the production site.  A few years ago I added a contact type of "Email" to go along with "In Person - Home", "In Person - Hospital", etc, but didn't update the index numbers used in the SFH-A report.  Because of where I inserted this contact type it only affected "Telephone Only" results, not any of the "In Person" ones.

Would you please close this if/when you agree that it's fixed?  Thanks.

**Comment by josephr5000** [comment]
@DaveSherwood any progress on confirming this fix?

**Comment by DaveSherwood** [comment]
I have retested and it appears to function correctly.
