### ISSUE TITLE
Call Center Login Restrictions - pop up message box incorrect 

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#188]
When trying to log in when Login Restrictions have been placed to preclude logging in based on whatever parameters have been set, you correctly are UNABLE to log in. The message that pops up, however, is WRONG. See screen below.

![capture](https://cloud.githubusercontent.com/assets/20777996/18853986/1f8434be-83fd-11e6-8b01-cf441c3184b2.PNG)

The message should be reworded to indicate that the reason you can’t log in is due to restrictions set to preclude login on such and such days at such and such times (Not “Login failed. Check username, password and conference, and try again.” Seeing that leads one to believe he/she simply typed in one of the three login requirements incorrectly - so they will continue to try and try again without success.

A more descriptive pop box is needed.

**Comment by josephr5000** [comment]
Good catch, but this one is by design.

You're 100% correct that this message does not fit the particular factor that's preventing this login.

However I deliberately chose not to reveal too much information about why logins fail, so as not to reveal too much information to someone trying to attack the system.  That's why I don't specify whether the error -- for example -- was with the username _or_ with the password.  Whatever you do, the message is fixed and generic.

Users whose login hours will be restricted are CC users without any legitimate reason (in the CC admin's judgment) to login outside their assigned shift.  They will have been told this.  If they forget, and get this error and are confused, they'll ask the CC admin who will remind them of the restriction.
