### ISSUE TITLE
Call Center - clicking on Verify Now for invalid email address sends Email Sent message

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#195]
Since the email address does not exist sending en Email Sent message should not happen. NO ERROR CHECKING.

**Comment by josephr5000** [comment]
Related to #194

**Comment by josephr5000** [comment]
I agree the system shouldn't even try to email to addresses that are syntactically invalid.

Just want to mention that emails can be syntactically valid yet not exist, and I have no way of knowing that in advance.  That's the whole point of doing verification! :-)  Example: j8989898989898989898989@gmail.com is valid but might very well not exist.  Just mentioning this since your complaint about is about trying emails that don't exist, which I can't entirely avoid.

**Comment by josephr5000** [comment]
Fixing validation in #194 would prevent this scenario from ever occurring, so am closing this as a duplicate of that one.
