### ISSUE TITLE
Call Center - entering letters, numbers and symbols in phone fields issue

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#196]
Phone number fields will accept invalid information.
Letters, symbols and decimals are incorrectly accepts as phone number.
NO ERROR CHECKING

**Comment by josephr5000** [comment]
BY DESIGN.

Many users enter explanatory text, eg:
**206-555-1212 case manager Jabez**

It isn't intended to be a field purely containing numbers.  It's intended to be flexible and forgiving of whatever variety of entry conferences might want to make.

Changing this would be a significant redesign as you'd have to decide what to do with current non-phone-number data that users have entered (example given above).
