### ISSUE TITLE
Question - leaving password and confirm password fields blank on Call Center's Current Members list?

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#198]
The member profile accepts the account with no email entries. Is this by design or a bug?

**Comment by josephr5000** [comment]
Your question above doesn't match the question in the title.  Don't fully understand what you're asking in the title, so I'll answer re email.

Email isn't currently *required* so it is *currently* BY DESIGN that it accepts accounts without any email specified.

With the email verification campaign my hope is to get all users to the point where they have provided email addresses.  Sometime soon I think we should start *requiring* email addresses for *new* accounts, but that decision hasn't been made yet.  That would be a fine enhancement request :-)
