### ISSUE TITLE
Call Center - not able to delete staff member or volunteer; and "Show/hide other members" does not work

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#208]
We have talked about the inability to delete people before. I agreed to have that be addressed as an enhancement down the road.
The "Show/hide other members" functions does NOT work at all at this time and needs to be fixed. Hopefully, sooner than later as it would permit hiding entries that should actually be deleted (such as the bogus entry I made when testing what could and could not go into fields). *However, this does not stop us from going live.*

**Comment by josephr5000** [comment]
You can never *delete* members in this product, anywhere, and haven't been able to since its inception.  You *can* set member status to *inactive* that makes the member unable to login and makes them disappear from all rosters.

Show/Hide Other Members works fine when there are others to show.  I just made the 11&etc member inactive, and you can now see them under "Show/Hide Other..."

**Comment by TomOwens5000** [comment]
My mistake. Apparently I did not refresh the screen and, after later having done so, discovered that I too can hide and unhide 11&etc member. So #208 can remain closed. And ... *However, this does not stop us from going live.* has become a moot point.

**Comment by TomOwens5000** [comment]
Suggest a LIKE classification for this one.

**Comment by josephr5000** [comment]
I don't get what the remaining issue is here that you LIKE.  Would you please clarify?  We've discussed above that you can't DELETE members and never have been able to.  That's unlikely to change since even long-departed members can still be referenced in historical records.  Inactivating them is a solution you seemed to like above.

The other topic, show/hide members, works fine.

So what remains?  Can we close this please, or clarify what the issue is.  That's why it's marked NOT_REPRO.
