### ISSUE TITLE
Conference Intake Settings are not displayed at Call Center

### ISSUE THREAD

**Issue by jln522** [josephr5000/confdb-public#214]
Set the Conference Intake settings for St.Jude Redmond. 
Then listing the Conference Intake Detail at Call Center the settings are not displayed.

URL http://confdb-test.azurewebsites.net/confdb/callcenter/IntakeDetail.asp?ConfID=17

**Comment by jln522** [comment]
Also the settings are not shown on Client File Page at Call Center.

**Comment by jln522** [comment]
The "Add New Request" button is grayed out because the Intake setting are not showing on at the Call Center.

**Comment by josephr5000** [comment]
When I log into St Jude, click Admin Pages, then Intake Settings: Status & Messages I don't see any indication that you have established any intake settings.

That being the case, it's BY DESIGN that there are no settings to display at the URL you included above, and that there are no settings to display on a client file page.

Could you try establishing settings, then log into the Call Center and revisit this?  You should see results then.

**Comment by jln522** [comment]
Hi Joseph;


I'm sure I "tried" to entered the settings, maybe I missed saving them. I'll try again.


Jim


Sent from Outlook<http://aka.ms/weboutlook>


________________________________
