### ISSUE TITLE
Call Center - Clients Turned-Away by Conference - 2 issues

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#235]
Part 1.
Clicking on "#Client-Days" invokes error message that reads:
"The page cannot be displayed because an internal server error has occurred." Search box test is moot until this is fixed.
Part 2.
Clicking the the Client's name invokes the Client File. Cannot be tested until Part 1 above is fixed.

Leaving open until fixed.

**Comment by TomOwens5000** [comment]
I'm confused.
This is what I reported but you have made no comments here.
It appears to me that you made comments on #224that should have gone here.

**Comment by TomOwens5000** [comment]
> .

**Comment by josephr5000** [comment]
I assumed resolving as duplicate would have been obvious without comment as there is a link to the duplicate.  224 is the older bug so it survived and I closed this one.

The second thing you complain about is just not being able to test, but fixing 224 resolves that as you *can* now test.  Again, didn't seem necessary to mention that explicitly, but since you ask, I am now.

Re-closing as there is nothing going on here.
