### ISSUE TITLE
Entering 2-digit YY in client DOB before 1950 gives negative age

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#240]
Not sure if this has already been brought up, but if you enter in a DOB Date, before 1950 (1949 & earlier), while using only the last 2 digits of the birth year, and (so far only in Chrome, not Internet Explorer), you will get a minus in age. 
![image](https://cloud.githubusercontent.com/assets/22033172/19094782/db122fd4-8a46-11e6-8163-9ad185c035fc.png)

**Comment by josephr5000** [comment]
FIXED

Two-digit years HIGHER THAN this year (now 16, next year 17, ...) will be assumed to be 19xx.  They can't be 20xx since that would be in the future, and DOB in the future makes no sense.

Two-digit years SMALLER THAN this year will be assumed to be 20xx.

Eg:
1/1/49 => 1/1/1949
1/1/20 => 1/1/1920
1/1/14 => 1/1/2014

**Comment by lisabarrientes** [comment]
Fixed. thanks!
