### ISSUE TITLE
Unnecessary message from Call Center

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#256]
If the CC looks at a client file but does not record a new request or turn away, clicks the "Done" button to exit (the only way to get off the page besides the back button on the mouse), a message is sent to the conference regarding  a "New intake from Call Center".  This will cause some confusion since there is no new intake.

**Comment by josephr5000** [comment]
NOT REPRO

Here's what I did:
- Log into CC
- Find/Create Files
- Search for any client in your conf, click their name to open Client File
- Press DONE (without doing *anything*)

I got this screen, which is the expected behavior.

![image](https://cloud.githubusercontent.com/assets/8585358/19414897/e0281f7e-9310-11e6-8bb7-4c19c1013f7a.png)

What are we doing differently?

**Comment by drodruck** [comment]
I don't understand.  I just logged (ccdougr) on and went to Heinrich in St. Monica's, hit Done and got this:
![image](https://cloud.githubusercontent.com/assets/20655031/19414923/26e59760-9312-11e6-8321-4d14c7f33842.png)

I also get one sent to MQP looking at a Mary Queen of Peace client, Speirs.

**Comment by josephr5000** [comment]
What browser?

**Comment by josephr5000** [comment]
Never mind, I *can* repro it using Heinrich.

**Comment by josephr5000** [comment]
I suspect the fact that St Monica is an intake-only conf where you pressed the RECEIVED button is the key distinguishing factor between St James (succeeded) and St Monica (failed).  I suspect you'll also find success if you try this with an MQOP client.

**Comment by drodruck** [comment]
I don't think it is just intake-only.  I get the following with MQP client speirs sent from DougUser at the Call Center:
![image](https://cloud.githubusercontent.com/assets/20655031/19415059/23518630-9318-11e6-9288-4f18f5c00d80.png)

**Comment by josephr5000** [comment]
Hmmmm, interesting.

FIXED (but please confirm that!).

It's interesting that others hadn't hit this sooner.  There was a window of opportunity since my last timezone fix on intake notifications until today where you'd basically ALWAYS get this.

It was checking for news by checking whether latest_change_on_file >= last_notified_change.  Should have been >.  Doing >= means it would always fire if the result were merely =, which is the case where you've made NO changes since the last notification.

**Comment by drodruck** [comment]
Confirm is fixed.
