### ISSUE TITLE
Show/Hide Payment Buttons - not working right on current production site

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#258]
Joseph,

Not sure how to test this on the beta site because I am not familiar with how to write checks, etc.
Will this be an issue in the new version we are working on?

Go to OL Guadalupe site.
Active File in question is HEYND, Wendy.
Assistance History...
   with Show/Hide Memos showing the memos - checked
   with Show/Hide Payment Buttons - checked

Uncheck Show/Hide Payment Buttons
Expect to see all PAID check listings to disappear.
They do not.

![capture](https://cloud.githubusercontent.com/assets/20777996/19320451/33f21d06-9066-11e6-903a-375118cd497a.PNG)

**Comment by josephr5000** [comment]
BY DESIGN.

Those green strips are NOT payment buttons, so they aren't affected.

Payment buttons say "PAY NOW" next to items WITHOUT green strips, ie: pledges that require payment.

To see any you'd have to (a) be a treasurer or assistant treasurer, and (b) have valuable PLEDGES (not prepaid or inkind) that have not yet been paid.

**Comment by TomOwens5000** [comment]
Thanks.
Closing.
