### ISSUE TITLE
CC testing by Lisa - generating gmail messages about new requests for existing clients

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#263]
Our intake person called this afternoon.
The gmail account listed new requests for existing clients.
A new request had been added so it looked to be a legitimate open case.
That caused a bunch of confusion but the worse issue is this.
The box that you click to go directly to the Active File was there and she clicked the link.
Took here directly into the test site. Later on she wondered why all our other active cases were no longer listed ... until we pointed out that she was in the test site.

**Comment by josephr5000** [comment]
It sounds like your gmail account got notification because you set it as the place for the new site to send intake notifications.  Did I understand that correctly?

If so, I would suggest the easiest fix would be to not do that, but to establish a fresh test account.

If there was something else that caused this chain of confusion, would you please help me understand what that was?

Thanks.

**Comment by TomOwens5000** [comment]
When we spoke before you suggested using the same gmail account, which I did.
I will take care of this one way or another - maybe a temporary new address - or maybe just changing to my email address for the time being.
Thanks for the prompt replies.
Closing.
Tom
