### ISSUE TITLE
Call Center should be able to see SHARED notes on closed files

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#304]
Currently the CC can not see public notes on closed cases.  It was decided that they be allowed to see all public notes even on closed cases.

**Comment by josephr5000** [comment]
FIXED.

@drodruck, would you please check from conf end to be sure you CAN still see shared and private notes?  Occurs to me you'll also need to check CC end to be sure they CANNOT see private notes since Lisa won't know a private note exists so cannot confirm it's invisible!  You have a CC login, so am assuming you can do this.

@lisabarrientes , would you please check from CC end to be sure you CAN see SHARED notes?

Whoever confirms last, please close this issue.  Thx.

**Comment by lisabarrientes** [comment]
It is confirmed.  Not sure if I’m last, but I need help in closing this.

Sorry, I forgot.

Lisa Barrientes
Helpline Center Manager
St. Vincent de Paul of Seattle|King County
5950 Fourth Avenue South|Seattle, WA 98108
P: 206-767-9975 Ext. 1131
E: lisab@svdpseattle.org<mailto:lisab@svdpseattle.org>

**Comment by josephr5000** [comment]
Lisa, thanks.  If you look above your comment (on github, NOT on email!!!!!!) you'll see @drodruck hasn't yet replied so you are NOT last.  No need for you to close it.

**Comment by drodruck** [comment]
Confirmed is fixed.
