### ISSUE TITLE
Edge browser issue when trying the read a file in the DocLib

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#325]
Okay, Joseph.
I tried the test on all three database web sites --- on a Windows 10 machine. You are right. It DOES occur on all 3 sites. Just never noticed it before because my machine is a Windows 7 machine.
I don't know if you can find a work-around or not but this is going to create frustration and confusion for lots of database users --- conferences other than ours too.

![capture](https://cloud.githubusercontent.com/assets/20777996/20659372/1164e8fc-b4f8-11e6-9ff2-c57d46de327e.JPG)

**Comment by josephr5000** [comment]
Changed title since it happens only on the Edge browser, not on Firefox or Chrome when running on Windows 10.

**Comment by josephr5000** [comment]
I don't know of a way to entirely avoid this question, but you CAN tell Edge that you'd like it to please just download the darned file without asking permission first.  Here's how:

1. Click settings

![image](https://cloud.githubusercontent.com/assets/8585358/20660014/015bbf72-b4fc-11e6-96eb-8c4172d22717.png)


2. Choose Advanced Settings

![image](https://cloud.githubusercontent.com/assets/8585358/20660023/0e70493a-b4fc-11e6-9677-6dc40b85cb39.png)


3.  Locate this particular setting

![image](https://cloud.githubusercontent.com/assets/8585358/20660025/157b4c5c-b4fc-11e6-97b2-b1ef36523da5.png)


4.  Turn it off

![image](https://cloud.githubusercontent.com/assets/8585358/20660031/1a6f6a9a-b4fc-11e6-8c31-fa646a6a2665.png)

5.  Then when you download you'll get this question which is familiar to Internet Explorer users since that's how it behaves when you download something.

![image](https://cloud.githubusercontent.com/assets/8585358/20660062/4509b1e8-b4fc-11e6-8a01-ee95f6b9a19f.png)

**Comment by TomOwens5000** [comment]
Thank you.
Your instructions on how to configure Edge worked just great on Karie's computer.
The way it works set up this way should not be confusing to anyone.
Keeping your instructions so if any of our Conference members question me I will be able to tell them how to configure Edge to avoid the confusion the default settings create.
