### ISSUE TITLE
Revisions to Intake Settings

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#346]
Just got a call from David Haywood (our President).  He wants our conference to be closed on the 22nd of December and start taking calls again on the 27th – and to let Lisa know now, ahead of time.

Looks like we may need some tweaking on the Intake: Status & Message screen to accomplish this electronically.  The way it is now "Conference Status" is either Open now or Closed now (the other choices not applicable here).  To be able to notify Lisa ahead of time we need the following.

In the Conference Status field --- add an “Expected Closing Date” choice.  And also add a new field in which to put the expected closing date. See illustration below.

![capture](https://cloud.githubusercontent.com/assets/20777996/21363866/2caf7a48-c6a3-11e6-9a87-f4b1f115dcf7.JPG)

**Comment by josephr5000** [comment]
For now you can solve this very easily.  Go in after the helpline closes on 12/21 and make the setting yourself.  It will take effect immediately, but since the helpline won't reopen until 12/22 that won't matter.

If you want Lisa to know in advance, suggest you send her an email.

If this is an enhancement request for 2017, please tag it accordingly so it can be revisited then.

Thanks!
