### ISSUE TITLE
Can a line for notes be added for the conferences to alert the Call Center about something? 2017?

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#349]
![image](https://cloud.githubusercontent.com/assets/22033172/21556692/bd15eca8-cdd7-11e6-8d88-9bbd8e289b82.png)

**Comment by josephr5000** [comment]
To answer your first question, yes, it is certainly *possible* to add a line like you showed above.

The next question is whether it is *desirable* to do so.  Is this the best way to solve their concerns?

My understanding was that the point of having *structured* questions with clear answers was to limit the amount of free-form text that your operators would have to read and understand during conversations with callers.  Allowing conferences space to write whatever they like will result in them writing exactly that -- whatever they like -- which could be all sorts of odd requests for your staff to grapple with.

Again, this is technically very easy to do.  I am only asking if it is the best solution to the problem.

REQUEST: could you please describe a couple of specific examples where this would be helpful so we can see what the underlying conference concern is, and whether there might be a more structured way to let them express that, something that limits them to clear questions and clear answers that are easier for your staff?

Thanks!

**Comment by lisabarrientes** [comment]
Well now I do not see any reason.  I just looked, and none now.

**Comment by josephr5000** [comment]
Ummmm, okay then.  That was quick!

The one example I recall was SVDP in Federal Way who wanted 12 foods on Monday and 2 rents on Tuesday, and you wondered whether a note could help explain to your operators which type of request went on which day, since the quota system only controls *quantity* and not *type*.

That issue might disappear Feb 1, so by itself it wouldn't justify much effort now to find some alternative.

If you come across other examples, let me know.  Until then, I'll leave this closed.

**Comment by josephr5000** [comment]
@lisabarrientes , I'm not sure why you reopened this without comment so I'm assigning back to you.  Please close, or add some comment about what should be done.

**Comment by lisabarrientes** [comment]
I was going to ask again, but then I lost the page and could not find it. Issue now reclosed.
