### ISSUE TITLE
Frequent Callers gives different values

### ISSUE THREAD

**Issue by DaveSherwood** [josephr5000/confdb-public#35]
Frequent callers does not produce the same value as the old DB. I entered a date of 2013 and number of calls at 3 and got different results.

**Comment by josephr5000** [comment]
Related to #36 .

Frequent Callers is a report that looks at all data from your threshold date (in this case, 2013) through today.  Since data after 4/22/16 differs between TEST and LIVE I would expect different results.

You didn't say precisely *what* results you're seeing, so I can't tell whether the differences are consistent with my explanation above.  If you think they are not, please provide specifics.
