### ISSUE TITLE
SVdP report productes different values for old DB

### ISSUE THREAD

**Issue by DaveSherwood** [josephr5000/confdb-public#36]
I ran the report for the last quarter 4/1/2016 to 6/30/2016 and got very different values. The total on the New DB was $2,594.69 and the old DB was $9962.82. Most of the counts are different. Maybe there is less data in the new but that isn’t what your email said.

**Comment by josephr5000** [comment]
This is expected.  The DB is a snapshot of the live data as of 4/22/16.  The live DB has presumably had much more fresh data added since then, so doing a comparison over these time periods would be expected to yield different results.

Please retry over a period prior to 4/22/16 and re-open if the problem persists.  If so, please say which conference, which time period, and provide results A and results B (either all or a representative sample) so I know what differences you're seeing.
