### ISSUE TITLE
Conference Website

### ISSUE THREAD

**Issue by ghost** [josephr5000/confdb-public#40]
ISSUE.  Need to be able to edit notes.  Person who made the note should be able to edit and modify it.  Administrator as well.  Often it is necessary to correct spelling mistakes and/or add, modify or delete comments.

**Comment by josephr5000** [comment]
Who is this? Could you pick a more descriptive username than 3tjo so other on the team know who you are?  Thanks.

Sent from Yahoo Mail on Android 
 
  On Sat, Jul 30, 2016 at 11:07, 3tjo<notifications@github.com> wrote:   
ISSUE. Need to be able to edit notes. Person who made the note should be able to edit and modify it. Administrator as well. Often it is necessary to correct spelling mistakes and/or add, modify or delete comments.

**Comment by josephr5000** [comment]
Fixed.  Here's a screenshot showing the Edit link that you'll see if EITHER (a) you're the author and the note is less than 2 weeks old, OR (b) you're an admin, since admins can edit everything.

![image](https://cloud.githubusercontent.com/assets/8585358/17843578/747e6abe-67e4-11e6-98bc-2105be3a66d9.png)

@tomowens5000
