### ISSUE TITLE
Call Center's Add New Client page should include Utility Acct Number

### ISSUE THREAD

**Issue by ghost** [josephr5000/confdb-public#42]
Spec 2.6 King County Help Line - Add New Client
Put back the Utility Acct Num field.  Have the call center get this information.  If the person making the home visit does NOT have this information BEFORE contacting the client they are unable to verify with the utility company the account number and amount owing prior to seeing the client. Otherwise it is necessary to contact the client twice: once to get the account number (then call the utility to confirm the information) and then call the client a second time to set up the appointment. This precludes the way we operate.

**Comment by josephr5000** [comment]
BY DESIGN.  The spec calls for that field to be removed.  Instead, the information is collected along with the request to which it pertains.  See the Add New Request screen, which looks like this:

![image](https://cloud.githubusercontent.com/assets/8585358/17507565/25524538-5dc5-11e6-9ee6-9355772861fd.png)

In general this provides better data because call center operators verify the information on every new request, plus it allows for different account numbers based on the request.  Eg: Water/Sewer/Garbage numbers are different that Electricity, which is different again from Telephone.
