### ISSUE TITLE
SFH Report Part A doesn’t appear to be working correctly

### ISSUE THREAD

**Issue by DaveSherwood** [josephr5000/confdb-public#47]
When I clicked on SFH Report A and set the range to last fiscal year, all values we zeros. I expected the report to match the old database report.

**Comment by josephr5000** [comment]
Update: successfully reproduced.  Am now investigating.

**Comment by josephr5000** [comment]
BY DESIGN.  I got curious about the fact that results for this FY seemed to appear fine, and re-examined the date profile of assistance history that I brought over to SQL Server.  I was reminded that I limited the size of the data import by restricting history to FY 2016 (ie: data since 10/1/15).  That being the case, I would expect a report on FY 2015 to produce zeroes (or close to that, in case new data has been added since data was migrated).

Would you please re-test on time periods between 10/1/15 and 4/1/16 and reopen this bug if you find any further problems in that time period?  Thanks.

@DaveSherwood
