### ISSUE TITLE
Missing Total Values on Treasury Report

### ISSUE THREAD

**Issue by DaveSherwood** [josephr5000/confdb-public#50]
When running a Treasury Report and looking at Last Fiscal Year, the last two values at the bottom of the report are missing. 
In the old DB the values of ($780.43) and $3,599.92 are shown.

**Comment by DaveSherwood** [comment]
Also, the Values for Total Expenses and Closing Balance are different. I would think these would be the same since the data should match.

**Comment by josephr5000** [comment]
Update:  I found that the critical factor in reproducing this (on my conference, St James-Bl Rosalie, anyway) appears to be the **end** date of the report.  Timeframes ending 6/21/16 or earlier work fine.  Timeframes ending 6/22/16 or later break.  Investigation continues.

**Comment by josephr5000** [comment]
FIXED.

Where there are no pledges in the report's date range, the query that calculates $ outstanding pledges returns NULL which displays as blank.  The last line is Cash - Outstanding, but Cash - NULL = NULL so that line also shows blank.

You saw it for Last Fiscal Year since that date range (10/1/14-9/30/15) has no pledges in it because my data import only went back to 10/1/15.

I saw it for end-dates after 6/21/16 because it looks back 60 days.  60 days before 6/21/16 is 4/22/16, the last day for which I imported underlying pledge and financial data.  So any end-dates 6/22 or later would have no pledges in the 60-day window, and you'd get NULL.

The fix is to replace NULL if/when it occurs with 0.
