### ISSUE TITLE
Browse/Find/Add Clients - Unacceptable time delay, etc.

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#93]
See attached file.

[Above screen shot is with software in development stage.docx](https://github.com/josephr5000/confdb-public/files/445605/Above.screen.shot.is.with.software.in.development.stage.docx)

**Comment by TomOwens5000** [comment]
DUPLICATE. Isn't this the same complaint as #93? Please reopen and clarify if it's a different issue. If you just want to add commentary, better to add such on #93 instead of opening a fresh issue about the same thing. Yes, I guess this is the same issue.

**Comment by TomOwens5000** [comment]
Additional items/comments ...
* Moving between fields produces slight movement of input boxes. Still not fixed on * Search * Search Filer response speed. Searching takes FOREVER in most cases.
* Current database has "flashing" indicator showing search is in process. That is missing or not functioning the development package.
* Click on Search For Voucher (with all search fields blank). The page cannot be displayed because an internal server error has occurred.
* Click on Search For Voucher (with at least one search field having been filled in). The page cannot be displayed because an internal server error has occurred.

**Comment by TomOwens5000** [comment]
How about this?
Why not use the same “Processing” button that appears when doing an Add New Request in the Open Requests section of the Client File?  This could be the standard approach for ALL items in the software that are processing or doing a search.  The processing would remain visible until the task at hand completes.

**Comment by josephr5000** [comment]
FIXED.  PLEASE REVIEW IMPORTANT NOTES BELOW
@drodruck  @TomOwens5000 

This fix essentially rewrites the plumbing for this feature, so please test it as if it is 100% new code.

KEY CHANGES

1. No longer searches as you type. I can reinstate that if folks *really* miss it, but it reduces load on the server to wait until you're finished typing and press SEARCH to indicate you're really ready for the server to do some work.
2. You can press ENTER to kick off a search, if you're in a hurry and don't want to reach for your mouse.
3. You no longer select to delete, but have single-serve X buttons next to each client that you can click to delete them one at a time.  The same technique is used in the Treasurer Pages to delete transactions.
4. Since deleting client files is IRREVERSIBLE and risks losing a lot of valuable information if you do it by accident or delete the wrong one, the system now has a more stringent confirmation check.  It no longer accepts you just pressing an OK button to confirm that you've read the warning.  It requires you to affirmatively type in the actual ID number of the client you wish to delete.  My hope is that if you really want to delete someone this isn't too hard, but there extremely low chance you'd ever do this by accident!

TESTING NOTES

1. Please specifically test each of the problems noted in the original report above to assure yourself that they are fixed to your satisfaction.
2. Please test user vs. admin for conferences, to be sure the delete buttons only appear to admins, and that everyone gets the Add New Client button after they've done at least one search.  Also confirm that results are only shown from the user's conference, and no others!
3. Please test both user and admin for call center to be sure: (1) no-one gets delete buttons, (2) Add New Client button appears as described above, (3) Results ARE taken from all conferences in the District (King County) but none from outside the county.

**Comment by josephr5000** [comment]
FYI @DaveSherwood @jln522
