### ISSUE TITLE
Treasury Pages - 4 failure items

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#97]
* Treasury Pages - click on New Payment. Result:  The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

* Treasury Pages - click on New Deposit. Result: The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

* Reports - Treasurer's Report - drill down on all Income items (1-5). Result: None of them work. Message: The page cannot be displayed because an internal server error has occurred. **Note that Income items 1-5 DO drill down as expected in the production version now being used live by conferences.**

* Reports - Treasurer's Report - drill down on Expense item Uncategorized. Result: The page cannot be displayed because an internal server error has occurred.

![screen](https://cloud.githubusercontent.com/assets/20777996/18140545/dbe11994-6f6a-11e6-931b-c40552813c97.png)

**Comment by josephr5000** [comment]
FIXED.

The key element in your items 1 & 2 above was that you were logged in NOT as Treasurer or Assistant Treasurer (which would give you read-write access) but as an Officer which gives you readonly access to finances.  In that case, clicking New Payment or New Deposit needs to redirect you since you don't have access to that, and the redirect was failing.

Your items 3 and 4 are the same underlying issue, and one that appears in a number of other places.  As part of migrating the database to SQL Server I decided to drop a very old Weblog table that I'd used to collect usage statistics but which I since found wasn't really as useful as I'd hoped.  The drill-down detail page still had a reference to the now-nonexistent Weblog.
