### ISSUE TITLE
Need to pick a more visible Edit label for Assistance History Edits

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#98]
Suggest instead of grayed out and underlined _Edit_ that we used the same thing we use in the current version, i.e., **Edit** (same blue as in current version of database and still underlined and placed to the right of the time stamp)

![xxx](https://cloud.githubusercontent.com/assets/20777996/18143551/65a5ee5a-6f77-11e6-87c5-9fd5b29ff7e5.png)

**Comment by josephr5000** [comment]
It's really by design to make it available but not have it be encouraging.  It's intended to be slightly hard to see, because in general I'm not comfortable providing encouragement to people to revise notes on closed cases.  

The text is now larger after recent reformatting.  I wonder if that makes it just easy enough to read to be tolerable?

**Comment by TomOwens5000** [comment]
Yes, the larger formatting is MUCH better.
Still would like to see "Edit" and "Delete" buttons more visible.
Understand why you like them in "subdued" video but I still would like to see them more visible so Conference members won't overlook them. All this goes to the issue of what types of editing and deleting are going to be allowed so I will close this one.
BUT HAVE STRONG FEELING ABOUT THE EDITING ISSUES!
